spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${HUBWORK_MAIL_USERNAME}
    password: ${HUBWORK_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

app:
  setup:
    count:
      user: 20
      business: 10